controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - front_left_wheel_joint
      - rear_left_wheel_joint

    right_wheel_names:
      - front_right_wheel_joint
      - rear_right_wheel_joint

    wheel_separation: 0.46
    wheel_radius: 0.08

    odom_frame_id: odom
    base_frame_id: base_link

    publish_rate: 50.0

    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    position_feedback: true
    open_loop: false
